### ISSUE TITLE
tegu startup logic can choose the wrong checkpoint file

### ISSUE THREAD

**Issue by robert-eby** [att/tegu#22]
The startup logic for tegu can pick the wrong checkpoint file to pass to Tegu if the last several checkpoint files were all created within the same second.  For example, right now i have 28 checkpoint files, but on restart tegu started with resmgr_b26.ckpt. This is because they are sorted by mod time, and Linux only keeps modification times to a granularity of a second.  Need a better way to arbitrate; either make sure each checkpoint is created within a unique 1 second period, or store metadata with each file to indicate millisecond granularity.

**Comment by ScottDaniels** [comment]
Fixed.   The checkpoint routine will only write a checkpoint if the last one was written long enough ago so as not to duplicate the timestamp in the file system.  If the checkpoint routine defers a checkpoint because of a possible conflicting timestamp, it will indicate a retry is necessary which will be noticed by the tickler driven checkpoint mechanism.  All changes that occur during the "delay" period will be captured in the next checkpoint file.

**Comment by ScottDaniels** [comment]
Closing this issue. Changes committed in: 9e185fe9edf74a6a9549840253c93e0b47c7cbcc
